# Generated by Django 3.1.2 on 2020-10-22 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Disease Name')),
            ],
        ),
        migrations.CreateModel(
            name='Lab_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Test Name')),
                ('cost', models.IntegerField(default=10)),
                ('start_value', models.CharField(max_length=15)),
                ('end_value', models.CharField(max_length=15)),
                ('units', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issued', models.DateTimeField(auto_now_add=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='report.disease')),
                ('doctor', models.ForeignKey(on_delete=models.SET('anonymous'), related_name='doctor', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Test_result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=15)),
                ('lab_test', models.ForeignKey(on_delete=models.SET('Test not avilable'), to='report.lab_test')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.report')),
            ],
        ),
        migrations.AddField(
            model_name='disease',
            name='tests',
            field=models.ManyToManyField(to='report.Lab_test'),
        ),
    ]
