# Generated by Django 3.1.2 on 2020-11-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(max_length=10, unique=True, verbose_name='phone'),
        ),
    ]
